jobs:
  updatecli:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Install updatecli
      uses: updatecli/updatecli-action@v2
    - continue-on-error: true
      env:
        UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Diff
      run: 'updatecli diff --config updatecli/updatecli.d --values updatecli/values.yaml

        '
    - continue-on-error: true
      env:
        UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/master'
      name: Apply
      run: 'updatecli apply --config updatecli/updatecli.d --values updatecli/values.yaml

        '
name: updatecli
on:
  repository_dispatch:
    types: trigger-ga___updatecli-action.yaml
